
stages:
#  - build
  - package
  - deploy-development



#services:
#  - docker:dind


#build:
#  image: docker:stable
#  stage: build
#  script:
#    - docker --version
#    - docker login registry.gitlab.com -u $USERNAME -p $ACCESS_TOKEN
#    - docker build -t registry.gitlab.com/kirakira11/photoshoot/$DOCKER_IMAGE_NAME .
#    - docker push registry.gitlab.com/kirakira11/photoshoot/$DOCKER_IMAGE_NAME

package:
  image: maven:3-amazoncorretto-17
  stage: package
  script:
    - java --version
    - mvn clean package -T 2C
  artifacts:
    paths:
      - "**/target/*.jar"


include:
  - "/photoshoot-master-user/.deployer.yml"
